site_name: Rea::App1
nav:
    - Home: index.md
    - Abstract: abstract.md
    - API: 
        - storage: 
            - stgData: storage/stgData.md
            - fsStorage: storage/fsStorage.md
            - awsStorage: storage/awsStorage.md
            - minIO: storage/minIO.md
        - tcpSocket:
            - protocal: socket/protocal.md
            - normalServer: socket/normalServer.md
            - normalClient: socket/normalClient.md
        - serial:
            - modbusMaster: serial/modbusMaster.md
        - gui:
            - basic:
                - edit: gui/basic/edit.md
                - check: gui/basic/check.md
                - combo: gui/basic/combo.md
                - radio: gui/basic/radio.md
                - swipe: gui/basic/swipe.md
                - autosize: gui/basic/autosize.md
                - twindow: gui/basic/twindow.md
                - msgdialog: gui/basic/msgdialog.md
            - component:
                - progress: gui/component/progress.md
                - log: gui/component/log.md
                - list: gui/component/list.md
                - treeNodeView: gui/component/treeNodeView.md
                - camera: gui/component/camera.md
                - io: gui/component/io.md
    - About: about.md
theme: readthedocs
