site_name: Rea::App1
nav:
    - Home: index.md
    - Abstract: abstract.md
    - API: 
        - storage: 
            - stgData: storage/stgData.md
            - fsStorage: storage/fsStorage.md
            - awsStorage: storage/awsStorage.md
            - minIO: storage/minIO.md
        - tcpSocket:
            - protocal: socket/protocal.md
            - normalServer: socket/normalServer.md
            - normalClient: socket/normalClient.md
        - serial:
            - modbusMaster: serial/modbusMaster.md
        - qsgShow:
            - qsgModel: qsg/qsgModel.md
            - qsgBoard: qsg/qsgBoard.md
            - qsgBoardPlugin: qsg/qsgBoardPlugin.md
        - gui:
            - basic:
                - edit: gui/basic/edit.md
                - check: gui/basic/check.md
                - combo: gui/basic/combo.md
                - radio: gui/basic/radio.md
                - autosize: gui/basic/autosize.md
                - twindow: gui/basic/twindow.md
                - msgdialog: gui/basic/msgdialog.md
            - component:
                - log: gui/component/log.md
                - treeNodeView: gui/component/treeNodeView.md
                - camera: gui/component/camera.md
    - About: about.md
theme: readthedocs
