site_name: Rea::App1
nav:
    - Home: index.md
    - Abstract: abstract.md
    - API: 
        - storage: 
            - stgData: storage/stgData.md
            - fsStorage: storage/fsStorage.md
            - awsStorage: storage/awsStorage.md
            - minIO: storage/minIO.md
        - tcpSocket:
            - protocal: com/protocal.md
            - normalServer: com/normalServer.md
            - normalClient: com/normalClient.md
    - About: about.md
theme: readthedocs