site_name: Rea::App1
nav:
    - Home: index.md
    - Abstract: abstract.md
    - API: 
        - storage: 
            - stgData: storage/stgData.md
            - fsStorage: storage/fsStorage.md
            - awsStorage: storage/awsStorage.md
            - minIO: storage/minIO.md
        - tcpSocket:
            - protocal: socket/protocal.md
            - normalServer: socket/normalServer.md
            - normalClient: socket/normalClient.md
        - serial:
            - modbusMaster: serial/modbusMaster.md
        - gui:
            - basic:
                - edit: gui/basic/edit.md
                - check: gui/basic/check.md
                - spin: gui/basic/spin.md
                - combo: gui/basic/combo.md
                - track: gui/basic/track.md
                - radio: gui/basic/radio.md
                - autosize: gui/basic/autosize.md
                - linechart: gui/basic/linechart.md
                - dynamicQML: gui/basic/dynamicQML.md
                - search: gui/basic/search.md
                - histogram: gui/basic/histogram.md
                - thistogram: gui/basic/thistogram.md
                - dialog:
                    - msgdialog: gui/basic/msgdialog.md
                    - file: gui/basic/file.md
                    - colorSelect: gui/basic/colorSelect.md
                - container:
                    - twindow: gui/basic/twindow.md
                    - swipe: gui/basic/swipe.md
                    - gridder: gui/basic/gridder.md
                    - flip: gui/basic/flip.md
                    - nest: gui/basic/nest.md
            - component:
                - progress: gui/component/progress.md
                - log: gui/component/log.md
                - status: gui/component/status.md
                - navigation: gui/component/navigation.md
                - matrix: gui/component/matrix.md
                - list: gui/component/list.md
                - treeNodeView: gui/component/treeNodeView.md
                - camera: gui/component/camera.md
                - io: gui/component/io.md
    - About: about.md
theme: readthedocs
