site_name: Rea::App1
nav:
    - Home: index.md
    - Abstract: abstract.md
    - API: 
        - storage: 
            - fsStorage: storage/fsStorage.md
            - awsStorage: storage/awsStorage.md
            - minIO: storage/minIO.md
        - gui:
            - component:
                - camera: gui/component/camera.md
                - io: gui/component/io.md
    - About: about.md
theme: readthedocs
