site_name: Rea::App1
nav:
    - Home: index.md
    - Abstract: abstract.md
    - API: 
        - storage: 
            - stgData: storage/stgData.md
            - fsStorage: storage/fsStorage.md
            - awsStorage: storage/awsStorage.md
            - minIO: storage/minIO.md
        - tcpSocket:
            - protocal: socket/protocal.md
            - normalServer: socket/normalServer.md
            - normalClient: socket/normalClient.md
        - serial:
            - modbusMaster: serial/modbusMaster.md
        - qsgShow:
            - qsgModel: qsg/qsgModel.md
            - qsgBoard: qsg/qsgBoard.md
            - qsgBoardPlugin: qsg/qsgBoardPlugin.md
            - imagePool: qsg/imagePool.md
        - gui:
            - log: gui/log.md
            - twindow: gui/twindow.md
            - msgdialog: gui/msgdialog.md
    - About: about.md
theme: readthedocs